# Generated by Django 5.0 on 2024-01-21 18:59

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=store.models.ProductImage.make_image_path, verbose_name='Фото'),
        ),
    ]
