# Generated by Django 5.0 on 2024-01-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(blank=True, choices=[(None, ''), ('new', 'new')], max_length=10, verbose_name='Состояние'),
        ),
    ]
